### ISSUE TITLE
interactive programming interface

### ISSUE THREAD

**Issue by abhsarma** [MUCollective/multidy#2]
output the default analysis as the user writes code with branches into the multiverse.
calling `parse_multiverse()` and `execute_default()` from within the inside function should work.

- [x] multiverse is parsed everytime code is added to the multiverse using inside

- [x] default analysis is executed and stored in the relevant cell of the multiverse table

- [x] provide a way for the user to inspect the execution of the default analysis

**Comment by abhsarma** [comment]
Should the default analysis be running in the global environment as well as the corresponding multiverse environment?

**Comment by mjskay** [comment]
For point 3 above, I would suggest overriding the `$` operator for variable extraction. So code like this would work:

```r
inside(M, {
  df = some_code_to_create_a_data_frame()
  df
})
## would output the value of `df` 
## (i.e. parses & executes the above code and returned the result)
```

The above code would also create a `df` variable inside the current analysis's environment. Then this would work:

```r
M$df
## would output the value of `df` from current analysis
```

This would make the simplification that overrides `$<-` to assign code into the multiverse (and execute the default analysis) be a small delta from typical R code. Say you have this code:

```r
df = some_code_to_create_df()
df
## outputs `df`
```

You could replace it with this:

```r
M$df = ~ some_code_to_create_df()
M$df
## outputs `df` from current analysis
```
