### ISSUE TITLE
A multiverse with no branches should still have one universe in it

### ISSUE THREAD

**Issue by mjskay** [MUCollective/multidy#21]
Currently a multiverse with no branches is empty:

```r
M = multiverse()
multiverse_table(M)
```
```
data frame with 0 columns and 0 rows
```

But it should be a single universe with no parameters; e.g. something like this:

```r
M = multiverse()
multiverse_table(M)
```
```
# A tibble: 1 x 3
  .parameter_assignment .code      .results
  <list>                <list>     <list>  
1 <list [0]>            <language> <env>  
```

because you should still be able to write code into the multiverse even if it has no branches, which would create a single universe, up until the point where you write in some code with branches in it.

**Comment by abhsarma** [comment]
It's initialised empty, but if you add some code like this:
```
M$x <- ~ 5
multiverse_table(M)
```

It creates :
```
# A tibble: 1 x 3
  .parameter_assignment .code      .results
  <list>                <list>     <list>  
1 <lgl [1]>            <language> <env> 
```

**Comment by mjskay** [comment]
That seems fine for now.

I wonder why an empty parameter assignment is a `list(NA)` ? I'd have thought it would be a `list()`

**Comment by abhsarma** [comment]
It should have been list( list() )
The outer list is the column type, and the inner list is actually an empty list
