### ISSUE TITLE
get_option_index_from_branch

### ISSUE THREAD

**Issue by abhsarma** [MUCollective/multidy#29]
Come up with a better pattern matching to extract the option

**Comment by mjskay** [comment]
If I can make a suggestion --- since you always have a `get_option_name` function, you could (and probably should) use that to do it so that you only have to change the definition of option names in one place. E.g. apply that function to all options and take the index that matches

**Comment by abhsarma** [comment]
Yeah, that sounds like a good idea. Thanks!
