### ISSUE TITLE
inside does not properly include single expressions

### ISSUE THREAD

**Issue by mjskay** [MUCollective/multidy#35]
This yields an error:

```r
M = multiverse()

inside(M, x <- 1)
inside(M, y <- 2)
```
```
Error in eval(.c, env) : incorrect number of arguments to "<-"
```

It appears that if you use `inside` with `{ ... }` it just sticks the expression in there, where it should probably wrap it in `{ ... }` ?

E.g. this output:

```r
M = multiverse()

inside(M, x <- 1)
code(M)
```
```
x <- 1
```

Should probably output `{x <- 1}`? 

The workaround for the above is this:

```r
M = multiverse()

inside(M, {x <- 1})
inside(M, {y <- 2})
```

But we should not require the braces if they aren't necessary.

**Comment by abhsarma** [comment]
I might be mis-remembering, but I think we'd discuss this once. The `<-` primitive in R evaluates the expression, so it cannot be captured using `enquo(s)` or `enexpr(s)`.

**Comment by abhsarma** [comment]
Oh sorry, it was for `$<-`. I will try to fix this.
