### ISSUE TITLE
Should multiverse expressions be tidy-eval'd?

### ISSUE THREAD

**Issue by mjskay** [MUCollective/multidy#36]
Because multiverse expressions are currently tidy-eval'd, won't conflicts happen if someone wants to use tidy eval unquoting (`!!` or `!!!`) in their own code --- won't it get evaluated by us first, causing it to break? Maybe we shouldn't be tidy-evaling the expressions ourselves.

People could still use interpolation if they wanted to by building the expression first using `quo` and then passing it in.

**Comment by mjskay** [comment]
If we decide the answer is "no", might want to add an arg to `branch` to allow lists to be passed in. E.g. an `.options` arg so something like this:

```r
set.seed(branch(seed, !!!1:100))
```

Could be replaced with this:

```r
set.seed(branch(seed, .options = 1:100))
```

Where `.options` would just be merged with everything in `...`

**Comment by ntaback** [comment]
Have you seen curly curly https://www.tidyverse.org/articles/2019/06/rlang-0-4-0/ ?

**Comment by ntaback** [comment]
> If we decide the answer is "no", might want to add an arg to `branch` to allow lists to be passed in. E.g. an `.options` arg so something like this:
> 
> ```r
> set.seed(branch(seed, !!!1:100))
> ```
> 
> Could be replaced with this:
> 
> ```r
> set.seed(branch(seed, .options = 1:100))
> ```
> 
> Where `.options` would just be merged with everything in `...`

.options is better than users dealing with tidyeval.

**Comment by abhsarma** [comment]
I think there is a broader problem here of declaring continuous variables in the multiverse?

Right now, we are just creating branches by capturing the arguments in branch. So everything after the first argument is taken as a value.

So using that tidy-eval step, this:

```r
branch(seed, !!!1:5)
```
 
becomes this:

```r
branch(seed, 1, 2, 3, 4, 5)
```

So anything passed to `.options` will need to be evaluated before the multiverse is parsed?

**Comment by mjskay** [comment]
Yeah, I think that's right --- you would evaluate the .options argument in the parent environment to inside_multiverse or whatever (i.e. the environment of whoever calls that function). So you might need to keep that frame around so that you can evaluate the expression passed to `.options` properly.

**Comment by abhsarma** [comment]
wait are you saying that for something like:

```r
inside(M,  {  set.seed(branch(seed, .option = seq(1, 10, by = 0.1))) })
```

we change it to, and evaluate this: `{  set.seed(branch(seed, !!!seq(1, 10, by = 0.1))) }` in the parent environment?

this isn't going to work because we can't evaluate the branch function. There's a very inelegant way of rewriting the code but I don't think that's the correct approach?

**Comment by mjskay** [comment]
I don't think so... I was thinking more that the value of `.options` would be evaluated when `inside` is called and then used to construct the list of options. So I guess at the point `inside` is evaluated you could re-write the `branch` expression in the code and insert the options returned by evaluating `.options`, or you could evaluate it again later if you store a reference to the calling frame of `inside`. 

So you wouldn't be re-writing it into a different tidy-eval'd thing (which goes back to the point that the whole multiverse should not be tidy-eval'd anyway). Unless you are only tidy-eval'ing the code inside the `branch()` call, which would maybe make sense?

**Comment by abhsarma** [comment]
Right sorry. I am definitely missing something because the only way I can think of doing that is some hackish thing by taking an expression like:

```r
an_expr = expr(set.seed(branch(seed, .option = 1:100)))
x = eval(an_expr[[2]][[".option"]], envir = global_env())

an_expr[[2]] = an_expr[[2]] %>%
  unname()

for (i in 1:length(x)) {
  an_expr[[2]][[i+2]] = x[[i]]
}
```

**Comment by mjskay** [comment]
this line:

```r
x = eval(an_expr[[2]][[".option"]], envir = global_env())
```

is along the lines of what I was thinking, but using the calling frame from `inside()` instead of `global_env()` (which I think would be `parent.frame()` as called within `inside()`, but I might be wrong).

For the rest of it it seems like there should be a simpler approach using subset assignment, but I think that was the general idea of what I meant.

But maybe the right approach is to tidy-eval the branch call (and only the branch call) instead of implementing `.options`?

**Comment by abhsarma** [comment]
Makes sense. I just feel like we are asking users who may not want to use tidy-eval to use tidy-eval, which is why the `.options` thing makes a lot of sense.

Although I don't like the idea, using tidy-eval within `branch` is also simpler?

**Comment by mjskay** [comment]
Hmm. I am less worried about implementation complexity, as neither solution is that complex and all of that is hidden from the user anyway.

Just to make sure we're on the same page, the two different approaches we're talking about are:

1. No tidy eval anywhere. The `.options` argument to `branch()` is evaluated in the environment that calls `inside()` and then expanded into arguments for that function. So this:

   ```r
   x_options = 1:5
   inside(M, {x = branch(x, .options = x_options)})
   ```

   is equivalent to:

   ```r
   inside(M, {x = branch(x, 1, 2, 3, 4, 5)})
   ```

   (incidentally i assume this would also work with the formula syntax for named branches, conditionals, etc?).

2. Tidy eval just for branch calls, evaluated in the environment that called `inside()`. So the equivalent of the above is this:

   ```r
   x_options = 1:5
   inside(M, {x = branch(x, !!!x_options)})
   ```

   But also, if someone wanted to they could do typical tidy eval stuff like this:

   ```r
   branch_1_name = "foo"
   inside(M, {x = branch(x, 
     branch_1_name ~ 1, 
     "bar" ~ 2
   )})
   ```

   Which would be equivalent to:

   ```r
   inside(M, {x = branch(x, 
     "foo" ~ 1, 
     "bar" ~ 2
   )})
   ```

   Which honestly might be useful, as otherwise it could be hard to program against this library if someone wanted to generate branch code in some way.

**Comment by abhsarma** [comment]
Wait do you mean?

```r
branch_1_name = "foo"
inside(M, {x = branch(x, 
  !! branch_1_name ~ 1, 
  "bar" ~ 2
)})
```

**Comment by abhsarma** [comment]
But besides that that's what I am talking about. Not using tidy-eval and using approach (1) makes it easier for people who don't use tidyverse. On the other hand, even for people who use tidyverse, picking up these syntactic styles might be complex, even if we provide them with examples? Since it is not very intuitive?

I don't see a problem with having both?

**Comment by mjskay** [comment]
(yeah that's what I meant, fixed it).

I'm not sure I'm a huge fan of having both since they are pretty much equivalent and would both require documentation anyway...

**Comment by abhsarma** [comment]
I don't know, I'm maybe leaning towards not using tidy-eval? Seems less intuitive?

**Comment by mjskay** [comment]
Works for me. Maybe let's start with no tidy-eval and if some use cases come up later where it's really needed we can revisit?

**Comment by abhsarma** [comment]
Sure. Should this also check for incorrect arguments? Since we are not really evaluating this?

**Comment by mjskay** [comment]
I'm not sure I follow what you mean?

**Comment by abhsarma** [comment]
So like we would look for continuous variables in the `.option` argument:
```r
branch(seed, .option = 1:100)
```

But if someone uses something like `.options` or something then should we send an error? This is going to be more complicated because we are not actually evaluating the branch function so any typos would just be swallowed.

**Comment by mjskay** [comment]
That sounds like a bit too many corner cases / not generic enough.

A more generic way would be that `.options` gets evaluated with the expectation being that the result is list or vector-like, and then the result of evaluating it is added to the arguments for the branch call

so this:

```r
branch(foo, "option1" ~ 1, .options = list("option2" ~ 2, "option3" ~ 3))
```

is equivalent to this (and maybe is re-written into it?):

```r
branch(foo, "option1" ~ 1, "option2" ~ 2, "option3" ~ 3)
```

I feel like that is the most generic approach. That would also support sequences automatically, as this:

```r
branch(foo, .options = 1:5)
```

Would evaluate the `1:5` and then re-write the branch into:

```r
branch(foo, 1, 2, 3, 4, 5)
```

Make sense?

**Comment by abhsarma** [comment]
Yeah, this should not be too difficult to implement

**Comment by abhsarma** [comment]
I'm running into another small problem. Something like this works:

```r
inside(M, {
  branch(foo, "option1" ~ 1, .option = seq(2, 10, by = 0.1))
})
```

But this does not. I believe that even though I am evaluating the `2:10`, R still stores it as "2:10" i.e. not parsing each integer separately, but all of them together. This is failing at the parsing stage. Any thoughts?

```r
inside(M, {
  branch(foo, "option1" ~ 1, .option = 2:10)
})
```

**Comment by mjskay** [comment]
Hmmm... point me at the relevant code chunk and I'll take a look? I think you can quote references to code in comments.

Also why `.option` and not `.options`? Not sure which makes more sense but the plural sounds better to me for a reason I can't put my finger on...

**Comment by abhsarma** [comment]
found some other bugs, so I'll update once those are fixed.

But yeah, I could just switch to `.options` it does sound better
