### ISSUE TITLE
Add a universe index column to the multiverse table

### ISSUE THREAD

**Issue by mjskay** [MUCollective/multidy#37]
See point 3 here: https://github.com/MUCollective/multidy/issues/33#issuecomment-513941426

Basically I think we need a column to uniquely index universes. Might want it to be a factor, since that will make it easier to do things like re-order it (e.g. for making visualizations where it is sorted by an effect size). Could call it `.universe`?

**Comment by abhsarma** [comment]
Oh shoot. I created an index column but did not give it a good name.
