### ISSUE TITLE
Scoping of functions which operate on the multiverse object

### ISSUE THREAD

**Issue by abhsarma** [MUCollective/multidy#4]
- [x] `inside()` should modify the object in place by adding code to the multiverse

- [x] `parse_multiverse()` should modify the multiverse in place

- [x]  ensure new functions pass unit tests

This will allow the package to be interactive, and allow getting the default analysis as output everytime.

**Comment by mjskay** [comment]
Should parse_multiverse even be user-facing?

My sense is that it should end up being an internal function that users don't call...

**Comment by abhsarma** [comment]
Yeah, you're right. I meant, we want `parse_multiverse()` to modify in-place as well. But that's not important is it?

**Comment by abhsarma** [comment]
Anyway, this is proving more difficult than I expected. I am currently just assigning the local copy of the multiverse object to the one in the global object with the `assign()`, but I think the recommendation is to rewrite it in C++?

**Comment by mjskay** [comment]
could look at the implementation of `magrittr::%<>%` if you're having trouble.

Re: parse_multiverse: yeah, since it's going to be used internally I don't think you have to worry about it.

**Comment by mjskay** [comment]
Like something like this (based on me just looking at the source of `magrittr::%<>%`:

```r
function(...) {
  parent <- parent.frame()

  # ... some code that figures our the lhs and rhs of the assignment

  eval(call("<-", lhs, rhs, parent, parent)
}

**Comment by abhsarma** [comment]
Oh I forgot about this one. The other thing that is making this problematic to solve is the dispatch for `$<-`. I think going to two levels up, instead of just one should solve the problem, but I haven't tried it yet.

**Comment by abhsarma** [comment]
Actually, even if parse_multiverse if not user facing, it cannot have copy-on-modify behavior. Basically, the next step is to have `parse_multiverse()` inside `inside()`. In that case both must modify-in-place

**Comment by mjskay** [comment]
Depends on how you implement it - it could be that the code in inside() is actually creating a copy, you're just assigning it back to the same variable as the last step before returning from inside()

**Comment by abhsarma** [comment]
> Like something like this (based on me just looking at the source of `magrittr::%<>%`:
> 
> ```r
> function(...) {
>   parent <- parent.frame()
> 
>   # ... some code that figures our the lhs and rhs of the assignment
> 
>   eval(call("<-", lhs, rhs, parent, parent)
> }
> ```

This approach breaks down if arguments are passed using the pipe. When using the pipe, the parent environment is not going to be one level up, and it's proving difficult to get the name of the expression to search which environment it is in using where(). Not sure what the workaround is.

**Comment by mjskay** [comment]
maybe using reference classes is the way to go then. could either keep a non-reference-class external interface where basically everything is actually stored internally using a single reference class, or expose it to the outside world. I would probably keep the functions as functions and not methods though
