### ISSUE TITLE
Examples of usage patterns

### ISSUE THREAD

**Issue by mjskay** [MUCollective/multidy#45]
This is an issue to collect examples of usage patterns, to be documented somewhere.

## swapping out functions

Given:

```r
some_fun(a, b, c)
```

Say you have different versions of the function (`some_fun_1` and `some_fun_2`) you want to be able to use instead of `some_fun`. The direct way of doing this would be:

```r
branch(foo, some_fun_1, some_fun_2)(a, b, c)
```

Which is a little unintuitive. The entire `branch(...)` gets replaced with either `some_fun_1` or `some_fun_2` within a given universe, but it is hard to read. A more readable pattern might be;

```r
some_fun <- branch(foo, some_fun_1, some_fun_2)
some_fun(a, b, c)
```

## using / reusing parameters as variables

If you use a parameter multiple times (or just want to define it upfront), you can assign it to a variable:

```r
some_value = branch(some_value, 1, 2, 3, 4, 5)

# ... somewhere else ...
x = some_value * 2
y = some_value + 2
```

One question is if we want some kind of syntax like this that works on unevaluated code? Or if we want an ability to retrieve values of branches? I think the more explicit form above might be clearer...

Since this wouldn't work with unevaluated code, you would have to make a function if you wanted to reuse things:

```r
some_fun = function(x) {
  branch(foo,
    x * 2,
    x + 2
  )
}

# ...somewhere later ...
x = some_fun(4)
y = some_fun(6)
```

**Comment by abhsarma** [comment]
I'll have a documentation page for the `branch` function even though it's not called anywhere. As I write this I realise it might just be useful to have a vignette on `branch` since it is a metaphor that we keep using and is not explained in detail separately

**Comment by mjskay** [comment]
Yeah good idea
