### ISSUE TITLE
create modify-in-place for `$<-.multiverse` 

### ISSUE THREAD

**Issue by abhsarma** [MUCollective/multidy#5]
We can't use the `$<-` operator on the multiverse as it doesn't support modify-in-place behavior. This might be because R creates a copy of the first argument passed (the multiverse object) in `*tmp*`.

Might have to switch back to a custom infix operator.

**Comment by mjskay** [comment]
Hmmm... What if we use an r6 object embedded in the multiverse to actually contain everything in it? Then it's fine if the wrapper is copy on modify semantics because the object it wraps that actually contains everything is properly updated
