### ISSUE TITLE
Travis CI Build error

### ISSUE THREAD

**Issue by abhsarma** [MUCollective/multidy#51]
The travis build has been throwing an error because it can't install / load gganimate: https://travis-ci.com/MUCollective/multidy/builds/138101117

Not sure what is going wrong here?

**Comment by mjskay** [comment]
ah, travis is a fickle beast. Usually when this kind of thing happens I do a search for the package name in the log and look at any relevant errors. Here we've got this:

> Error: package or namespace load failed for ‘gganimate’:
>  .onLoad failed in loadNamespace() for 'gganimate', details:
>   call: NULL
>   error: The png package is required to use gifski_renderer
> Error: loading failed

which suggests to me that you might need to add the `png` package to `Suggests:` in the `DESCRIPTION` file. Probably `png` is a soft dependency somewhere up the chain so it doesn't get auto-installed by travis.

**Comment by abhsarma** [comment]
I see. Okay, I pushed a commit so should be fixed. Funny, because gganimate we've been using here for a while and never got this error

**Comment by mjskay** [comment]
Probably they changed something upstream. It happens, it is why Travis is both so useful (these bugs get caught so users dont have to deal with them) and so frustrating (any time I go back to a project I haven't touched in awhile there's a good chance Travis breaks even though I don't change anything).
